version: '2.1'

volumes:
  geoserver-extensions:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './geoserver_extensions'
  geoserver-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './geoserver_data'
  geo-db-data:

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "25434:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:${GEOSERVER_VERSION_TAG}
      volumes:
        - geoserver-data:${GEOSERVER_DATA_DIR}
        - geoserver-extensions:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib
      ports:
        - "8600:8080"
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
