version: '2.1'

services:
   geoserver:
      image: ene-docker.iiasa.ac.at/kartoza-geoserver:${GEOSERVER_VERSION_TAG}
      volumes:
        - /opt/ene-geoserver-hotspots.iiasa.ac.at/geoserver_data_dir:${GEOSERVER_DATA_DIR}
      ports:
        - "8222:8080"
      restart: always
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      container_name: ene_geoserver
      healthcheck:
        test: curl --fail -s http://localhost:8080/geoserver/web || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
